### ISSUE TITLE
hub-client dependency error

### ISSUE THREAD

**Issue by acdcjunior** [c3pr/node-c3pr-hub-client#1]
```
> c3pr-repo-gitlab@14.0.0 start /opt/c3pr-repo-gitlab
> node --require ts-node/register src/index.ts


/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:253
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/application/PullRequestRequested/handlePullRequestRequested.ts(4,23): error TS2497: Module '"/opt/c3pr-repo-gitlab/node_modules/node-c3pr-hub-client/events/registerNewEvent"' resolves to a non-module entity and cannot be imported using this construct.
src/application/PullRequestRequested/handlePullRequestRequested.ts(13,56): error TS2345: Argument of type '{ event_type: string; handlerFunction: (pullRequestRequestedEvent: Event<any>, { lcid, sha, euuid...' is not assignable to parameter of type 'FirstCollectedEventHandler'.
  Types of property 'handlerFunction' are incompatible.
    Type '(pullRequestRequestedEvent: Event<any>, { lcid, sha, euuid }: { lcid: any; sha: any; euuid: any; ...' is not assignable to type '(event: any, log: any) => HandlerOutput | Promise<HandlerOutput>'.
      Type 'Promise<{ new_status: string; result: void | { new_status: string; result: { error: any; meta: { ...' is not assignable to type 'HandlerOutput | Promise<HandlerOutput>'.
        Type 'Promise<{ new_status: string; result: void | { new_status: string; result: { error: any; meta: { ...' is not assignable to type 'Promise<HandlerOutput>'.
          Type '{ new_status: string; result: void | { new_status: string; result: { error: any; meta: { pullRequ...' is not assignable to type 'HandlerOutput'.
            Type '{ new_status: string; result: void | { new_status: string; result: { error: any; meta: { pullRequ...' is not assignable to type 'HandlerOutput'.
              Types of property 'new_status' are incompatible.
                Type 'string' is not assignable to type '"PROCESSED" | "UNPROCESSED"'.

    at createTSError (/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:253:12)
    at getOutput (/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:363:40)
    at Object.compile (/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:551:11)
    at Module.m._compile (/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:435:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/opt/c3pr-repo-gitlab/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! c3pr-repo-gitlab@14.0.0 start: `node --require ts-node/register src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the c3pr-repo-gitlab@14.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-15T21_06_44_962Z-debug.log
```

**Comment by acdcjunior** [comment]
fixed
